/**
 * Created by chengfei on 2017/2/17.
 */
export const ADD_TO_CART = 'ADD_TO_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'

//登录
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_OUT = 'LOGIN_OUT';
// 创建广告
export const CREATE_ADS_SUCCESS  = 'CREATE_ADS_SUCCESS';
export const CREATE_ADS_FAILURE  = 'CREATE_ADS_FAILURE';
// 广告列表
export const CHECKOUT_ADS_SUCCESS = 'CHECKOUT_ADS_SUCCESS';
export const CHECKOUT_ADS_FAILURE = 'CHECKOUT_ADS_FAILURE';
// 广告详情
export const CHECKOUT_ADSBYID_FAILURE = 'CHECKOUT_ADSBYID_FAILURE';
// 执行上下线
export const UPDATE_ADVER_SUCCESS = 'UPDATE_ADVER_SUCCESS';
// 删除广告
export const DELETE_ADVER_SUCCESS = 'DELETE_ADVER_SUCCESS';
// 暂存页面信息
export const SAVE_PAGE_SUCCESS = 'SAVE_PAGE_SUCCESS';
export const START_LOADING = 'START_LOADING';
export const FINISH_LOADING = 'FINISH_LOADING';

export const FETCH_HOME_SUCCESS = 'FETCH_HOME_SUCCESS'
export const FETCH_HOME_FAILURE = 'FETCH_HOME_FAILURE'
