/**
 * Created by chengfei on 2017/2/17.
 */
export const ADD_TO_CART = 'ADD_TO_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'

//登录
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_OUT = 'LOGIN_OUT';
// 创建广告
export const CREATE_ADS_SUCCESS  = 'CREATE_ADS_SUCCESS';
export const CREATE_ADS_FAILURE  = 'CREATE_ADS_FAILURE';
// 广告列表
export const CHECKOUT_ADS_SUCCESS = 'CHECKOUT_ADS_SUCCESS';
export const CHECKOUT_ADS_FAILURE = 'CHECKOUT_ADS_FAILURE';
// 广告详情
export const CHECKOUT_ADSBYID_FAILURE = 'CHECKOUT_ADSBYID_FAILURE';
// 执行上下线
export const UPDATE_ADVER_SUCCESS = 'UPDATE_ADVER_SUCCESS';
// 删除广告
export const DELETE_ADVER_SUCCESS = 'DELETE_ADVER_SUCCESS';
// 暂存页面信息
export const SAVE_PAGE_SUCCESS = 'SAVE_PAGE_SUCCESS';
export const START_LOADING = 'START_LOADING';
export const FINISH_LOADING = 'FINISH_LOADING';

export const FETCH_HOME_SUCCESS = 'FETCH_HOME_SUCCESS';
export const FETCH_HOME_FAILURE = 'FETCH_HOME_FAILURE';

//获取优惠劵列表
export const CHECKOUT_CONPON_SUCCESS = 'CHECKOUT_CONPON_SUCCESS';
export const CHECKOUT_CONPONINFO_SUCCESS = 'CHECKOUT_CONPONINFO_SUCCESS';
export const DELETE_CONPON_SUCCESS = 'DELETE_CONPON_SUCCESS';
export const UPDATE_CONPON_SUCCESS = 'UPDATE_CONPON_SUCCESS';

//获取地区信息
export const CHECKOUT_AREAS_SUCCESS = 'CHECKOUT_AREAS_SUCCESS';

//智鸣系统
export const SET_CITY_DIVISION = 'SET_CITY_DIVISION';
export const SET_CURCITY = 'SET_CURCITY';
export const SET_COORDINATES = 'SET_COORDINATES';
export const SET_AREA_BIKE_LIST = 'SET_AREA_BIKE_LIST';
export const CLEAR_AREA_BIKE_LIST = 'CLEAR_AREA_BIKE_LIST';
export const SET_AREA_BIKE_INFO_LIST = 'SET_AREA_BIKE_INFO_LIST';
export const CLEAR_AREA_BIKE_INFO_LIST = 'CLEAR_AREA_BIKE_INFO_LIST';
export const SET_BIKES_DETAIL_INFO = 'SET_BIKES_DETAIL_INFO';

//阶梯计价
export const SET_PRICE_MODEL_LIST = 'SET_PRICE_MODEL_LIST';
export const SET_PRICE_LIST = 'SET_PRICE_LIST';
export const SET_CUR_PRICE_MODEL = 'SET_CUR_PRICE_MODEL';
